### ISSUE TITLE
Why separate window for Governor options?

### ISSUE THREAD

**Issue by frank-zago** [BrokenRegistry/Rotp-Fusion#105]
The Option settings are in an overlay over the galaxy view, so why is the governor a separate window and not something similar?

**Comment by BrokenRegistry** [comment]
The modder, who originally made the Governor, implemented it long before I modified the options interfaces. Only the options in the rectangles were available, they were extremely hard to create and modify, and they were not accessible from the galaxy map.
He chose to use a graphic creation tool that greatly simplifies the coding of the interface, but is not compatible with the game interfaces. (And in addition the colors were not harmonized, click on "Original view"to see what it looked like)
I have since simplified the creation of the options interfaces (it is now child's play), and added a compact version allowing the display of a greater number of options, and made them accessible from the game interface.
I then added a page with the Governor options, because the Governor did not always display in full screen mode, and was not accessible during the initial configuration either.
And finally, I gave colors to the original Governor panel in the Rotp spirit, but the base panel is still generated automatically by the graphics tool.
Another advantage is that you can also keep the Governor panel open permanently, and move it to a secondary display.
