### ISSUE TITLE
inconsistent window guide color

### ISSUE THREAD

**Issue by frank-zago** [BrokenRegistry/Rotp-Fusion#106]
In the options window, when the guide is on (lower left) the background color of the help window is a light brown. When the guide is not on, and F1 is used for an option, the background is white. 

The content is also slightly different, with the Selected Value not displayed in one case. 

IMO the same info should be displayed in both case, the same way.

**Comment by BrokenRegistry** [comment]
Call it a feature!
F1 is tied to vanilla help, which is not HTML compatible (except for the <br> handling I added). This help is used everywhere and converting it to HTML is far from an easy task.
That's why I created a separate "Guide" that can display basic HTML (Java is limited to Html2). I could only include this guide in the options panels.
The Guide can use _HELP labels, while F1 is limited to _DESC labels. This explains the difference in content.
I kept the original colors of F1 to avoid confusion (and for simplicity).
