### ISSUE TITLE
selecting a different ship set doesn't refresh the ships on start screen

### ISSUE THREAD

**Issue by frank-zago** [BrokenRegistry/Rotp-Fusion#115]
New bug today.

**Comment by BrokenRegistry** [comment]
This one will not be easy, as this only happen on the github release!
It works fine on my IDE???

**Comment by frank-zago** [comment]
Worked fine yesterday. Fails today. It's the 6 ships on the race selection screen.

**Comment by BrokenRegistry** [comment]
So strange!
I restarted my computer, and the bug was there on my IDE... Then everything worked again.
Same thing with the Github release... After playing a bit with the species and custom species, it works.
Closing the game and restarting it will not bring back the bug...???
How mysterious... 
I'll hunt it.

**Comment by frank-zago** [comment]
Selecting a different race will display its own ships, not matter what the Ship Set setting is changed to.

**Comment by BrokenRegistry** [comment]
Yes, I found the what trigger the fix! Go in the custom Species and select one on the right column, and set it as Player.
Everything will works fine, event if you unselect the checkbox...
I know where to search now!

**Comment by BrokenRegistry** [comment]
It was a nasty bug. Due to the merging of "Original" and "Display Race" in the "Select Your Empire" panel. Both are needed, but one per panel is enough.
Fixed
