### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by peyre** [BrokenRegistry/Rotp-Fusion#44]
I love the frequent releases of this Fusion Mod!  I've noticed though that the changelog seems to be cumulative: changes made to previous releases are included with each new one.  Perhaps each release could just show what _it_ does?  You can look down the page at previous releases to see what they've modified.

**Comment by BrokenRegistry** [comment]
It is not easy to satisfy everyone, originally the "readme.md" file which contains what you ask was the one displayed.
Then people complained that it lacked an overview! As this file is displayed by default in the "code" tab, the release notes file was changed to only contains the differences between two reddit announcements.
(There is a better follow-up on the Discord Rotp.)
It could also be confusing that recently, many versions have been released without any new features, this because I'm building an interface for blind people, and new added elements are only spoken in Discord.
I'll add a warning in the next release!

**Comment by peyre** [comment]
Oh, ok!  Well if you did it this way partly because others complained about it being the way I suggested, I wouldn't recommend going back to that.  Thanks for getting back to me.
