### ISSUE TITLE
Diplomacy messages are sometimes in bold, sometimes not

### ISSUE THREAD

**Issue by frank-zago** [BrokenRegistry/Rotp-Fusion#80]
Some races talk in bold, some don't. But the next message can be back in thin lettering. This is inconsistent, and also rather new. Anything to do with the GNN font change?

**Comment by BrokenRegistry** [comment]
A test is done before writing a GNN Message. If the GNN font is not able to display all characters, a replacement font is chosen.
The replacement font is the one used to display and edit the star names.
I'll switch to a thinner font with the same set of characters.
Note: If the affected GNN messages do not have Greek characters, it may be due to some unsupported French characters... Tell me if this is the case, as it will justify to permanently change the French GNN Font.

**Comment by frank-zago** [comment]
This is in diplomacy communications, not GNN.

**Comment by BrokenRegistry** [comment]
The "GNN Font" is also used in some diplomacy communications, whose may also refert to star systems. So every use of this limited font is tested before being set.
I'll try to test every French label & dialogue when they are loaded to identify missing latin characters.

**Comment by BrokenRegistry** [comment]
The dialog font (GNN font) do not incude accented letters, nor unbreakable space... Thus unusable for French language.
-> replaced by the current "plainFont" police.
This police will also be used in other language when the text is incompatible with dialogFont. (Instead of the thicker one used before)

**Comment by frank-zago** [comment]
Merci. C'est beaucoup mieux ainsi.
