### ISSUE TITLE
more hardcoded strings to fix

### ISSUE THREAD

**Issue by frank-zago** [BrokenRegistry/Rotp-Fusion#87]
I think this appears in the Options menu. Not translatable as is.

    private static String yesOrNo(boolean b) {
        return b ? "YES" : "NO";
    }
    private static boolean yesOrNo(String s) {
        return s.equalsIgnoreCase("YES");
    }

**Comment by BrokenRegistry** [comment]
Only used for the content of the configuration file "Remnant.cfg".
It will be a very bad idea to try to translate this file, as it has to be loaded before the language is set (It contains hardware configuration... and language configuration.)
This configuration file is in plain text for backward compatibility, you don't need to open it.

**Comment by frank-zago** [comment]
So maybe it's from somewhere else. The Options window ('O') contains a mix of translated text and these Yes/No.

**Comment by BrokenRegistry** [comment]
I'll take a look.

**Comment by BrokenRegistry** [comment]
The content of these panels are mostly defined by the labels starting with SETTINGS_MOD_
I've translated some.

**Comment by frank-zago** [comment]
I don't think this is fixed.

This one is correct:
    SETTINGS_MOD_DISABLE_AUTO_HELP_YES        | Oui
    SETTINGS_MOD_DISABLE_AUTO_HELP_NO         | Non
    SETTINGS_MOD_DISABLE_AUTO_HELP_NEVER      | Jamais
    SETTINGS_MOD_DISABLE_AUTO_HELP            | Désactiver l'aide automatique : %1

That one stills says Yes/No:
    SETTINGS_MOD_DISABLE_ADVISOR_YES  | Désactivé
    SETTINGS_MOD_DISABLE_ADVISOR_NO   | Activé
    SETTINGS_MOD_DISABLE_ADVISOR      | Désactiver le conseiller : %1
    SETTINGS_MOD_DISABLE_ADVISOR_DESC | Activer / Désactiver l'affichage automatique des conseils de l'écran Galaxie lors du démarrage d'un nouveau jeu.

Even the English version prints Yes/No instead of Disabled/Enabled.knm

**Comment by frank-zago** [comment]
The source could be this one (from util/AbstractParam.java):

    static String yesOrNo(boolean b) { return b ? "Yes" : "No"; }

**Comment by frank-zago** [comment]
Indeed it is. Over 20 strings in the Option screen use that yesOrNo() function.

**Comment by BrokenRegistry** [comment]
Yes, It's still a backward compatibility issue.
As the "AbstractParam" also read and write the "remnant.cfg" file, it needs to use this conversion too...
But since the "Guide" integration is now quite completed, there should be enough tools to link the displayed value to the "BOOLEAN_YES" and "BOOLEAN_NO" labels. I'll try and see if it corrupt the "remnant.cfg" file.
Note: There is also another issue linked to the boolean parameters...
Most of the _YES and _NO are used as descriptions and should be named _YES_DESC and NO_DESC.
The _YES and _NO labels should be reserved for the selection text.
I'll try to fix that too.

**Comment by BrokenRegistry** [comment]
I was able to fix all without corrupting the "remnant.cfg" file.
The _YES and _NO labels are now used to replace the standard yes/No display values.
_YES_DESC and NO_DESC. Are for the description,  to replace the standard "To enable this option"/"To disable this option"
